### ISSUE TITLE
fiducials? 

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/hardware#36]
What’s a fiducial and what’s it doing there on my PCB?

**Comment by repollo** [comment]
Fiducials are used as reference points/markers in pick-and-place machines for precise component placement, this is used a lot in Surface Mount Technology. Otherwise computers would have a hard time trying to install an SMD component on a PCB.

**Comment by CamDavidsonPilon** [comment]
:) thanks @repollo
