### ISSUE TITLE
Blue and white LEDs emitting some light even when driver is set to 0

### ISSUE THREAD

**Issue by CamDavidsonPilon** [Pioreactor/hardware#37]

**Comment by VitorFrost** [comment]
did you read it with an oscilloscope?
this happens always, or this happens when something else is on? This is common with interference from motors or even wi-fi.

**Comment by CamDavidsonPilon** [comment]
I haven't read it with an oscilloscope. It seems to be something with our LED driver circuit. There's no problem with red / IR leds, but there is with higher frequency LEDs - probably something to do with the forward voltage of them.
