### ISSUE TITLE
Agitation fan overheating for high viscosity medium?

### ISSUE THREAD

**Issue by VitorFrost** [Pioreactor/hardware#45]
Ok, I have tried to build an magnetic stirrer with 12V fan, but I got a fast overheating of the fan, specially with higher viscosity medium.
Had you monitored it? 
Had you tried it with high sugar concentration medium?
Some cells form filaments/blobs, that also creates trouble for bioreactors.

**Comment by CamDavidsonPilon** [comment]
I've had no problems with up to a 10% YPD mix (not _very_ viscous), and moving ~20ml. Your volume is much more, though, right? 

The software is agnostic to the voltage of motor. The default `stirring` job that we use just controls the DC% of a PWM signal applied to the motor. (The pioreactor hardware supports an auxiliary power supply of up to 18V, but by default it's 5v). 

For moving high viscosity, high volumes, you may need to upgrade to a brushed motor, but the same logic applies (control stirring speed via a PWM signal). 

> Some cells form filaments/blobs, that also creates trouble for bioreactors.

Like biofilms? Yea, always a concern. I haven't had much trouble with biofilms (yet) though.
